# Service para aplicação FIAP SOAT
apiVersion: v1
kind: Service
metadata:
  name: fiap-soat-app
  namespace: fiap-soat
  labels:
    app: fiap-soat-app
    project: fiap-soat-fase3
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # COMENTADO para economia - usar NodePort em vez de LoadBalancer
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: NodePort  # Economia AWS Academy - sem Load Balancer
  # type: LoadBalancer  # Descomente se quiser LB (custa ~$16/mês)
  
  selector:
    app: fiap-soat-app
  
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30080  # Porta fixa para NodePort
  
  sessionAffinity: None
---
# Service interno para comunicação entre pods
apiVersion: v1
kind: Service
metadata:
  name: fiap-soat-app-internal
  namespace: fiap-soat
  labels:
    app: fiap-soat-app
    type: internal
spec:
  type: ClusterIP
  selector:
    app: fiap-soat-app
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
---
# HorizontalPodAutoscaler (HPA) - Opcional
# Comentado para economia - t3.micro tem recursos limitados
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-soat-app-hpa
  namespace: fiap-soat
  labels:
    app: fiap-soat-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-soat-app
  
  minReplicas: 1
  maxReplicas: 2  # Máximo baixo para AWS Academy
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
