apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-soat-nestjs
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-nestjs
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-soat-nestjs
  template:
    metadata:
      labels:
        app: fiap-soat-nestjs
        version: "1.0"
    spec:
      containers:
      - name: nestjs-app
        image: 280273007505.dkr.ecr.us-east-1.amazonaws.com/fiap-soat-nestjs-rds-app:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: fiap-soat-config
        - secretRef:
            name: fiap-soat-secrets
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"