apiVersion: v1
kind: Service
metadata:
  name: fiap-soat-nestjs-service
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-nestjs
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: fiap-soat-nestjs
    app: fiap-soat-nestjs