# FIAP SOAT - Real NestJS Application Deployment using Docker Hub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-soat-nestjs-real
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-nestjs-real
    version: v1
    component: backend
    source: dockerhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-soat-nestjs-real
  template:
    metadata:
      labels:
        app: fiap-soat-nestjs-real
        version: v1
        component: backend
        source: dockerhub
    spec:
      containers:
      - name: fiap-soat-nestjs
        image: fiapsoat/nestjs-app:latest
        imagePullPolicy: IfNotPresent  # Usar imagem local se push falhou
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Configurações básicas para demo (em produção usar ConfigMap/Secrets)
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres123"
        - name: DB_DATABASE
          value: "soat_tech_challenge"
        - name: JWT_SECRET
          value: "fiap-soat-jwt-secret-key-prod"
        - name: MERCADOPAGO_ACCESS_TOKEN
          value: "TEST-demo-token"
        # Health checks específicos para NestJS
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        # Resource limits otimizados para NestJS
        resources:
          requests:
            memory: "768Mi"
            cpu: "300m"
          limits:
            memory: "1.5Gi"
            cpu: "800m"
