name: Terraform CI/CD - EKS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform EKS
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      id-token: write

    env:
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Configure kubectl
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name fiap-soat-eks-dev

      - name: Deploy Kubernetes Manifests
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ../../manifests
          kubectl apply -f namespace.yaml
          kubectl apply -f configmap.yaml
          kubectl apply -f secret.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for Deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          kubectl rollout status deployment/fiap-soat-nestjs -n fiap-soat-app --timeout=5m

      - name: Verify Pods
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "=== Pods Status ==="
          kubectl get pods -n fiap-soat-app
          echo ""
          echo "=== Service Status ==="
          kubectl get svc -n fiap-soat-app
          echo ""
          echo "=== Deployment Logs (last 50 lines) ==="
          kubectl logs -n fiap-soat-app deployment/fiap-soat-nestjs --tail=50 || true
